- name: Basic server setup
  hosts: servers
  become: yes  # Run tasks with sudo privileges

  roles:
    - system_updates
    - logging_setup
    - time_configuration
    - ssh_setup
    - user_management
    - package_installation
    - security_setup
    - automatic_updates

  vars:
    SSH_KEY_PATH: "{{ lookup('env', 'SSH_KEY_PATH') }}"
    NEW_USER_PASSWORD: "{{ lookup('env', 'NEW_USER_PASSWORD') }}"
    NEW_USER_NAME: "{{ lookup('env', 'NEW_USER_NAME') }}"
    ANSIBLE_USER: "{{ lookup('env', 'ANSIBLE_USER') }}"
    TIMEZONE: "{{ lookup('env', 'TIMEZONE') }}"
