- name: Basic server setup
  hosts: servers
  become: yes  # Run tasks with sudo privileges

  roles:
    - { role: system_updates, tags: ['system', 'updates'] }
    - { role: logging_setup, tags: ['logging'] }
    - { role: time_configuration, tags: ['time'] }
    - { role: ssh_setup, tags: ['ssh'] }
    - { role: user_management, tags: ['users'] }
    - { role: package_installation, tags: ['packages'] }
    - { role: security_setup, tags: ['security'] }
    - { role: automatic_updates, tags: ['updates', 'automatic'] }

  vars:
    SSH_KEY_PATH: "{{ lookup('env', 'SSH_KEY_PATH') }}"
    NEW_USER_PASSWORD: "{{ lookup('env', 'NEW_USER_PASSWORD') }}"
    NEW_USER_NAME: "{{ lookup('env', 'NEW_USER_NAME') }}"
    ANSIBLE_USER: "{{ lookup('env', 'ANSIBLE_USER') }}"
    TIMEZONE: "{{ lookup('env', 'TIMEZONE') }}"
