all:
  hosts:
    web_server:
      ansible_host: 192.168.1.100
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    db_server:
      ansible_host: 192.168.1.101
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    app_server:
      ansible_host: 192.168.1.102
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
