---
# Root user SSH setup
# Create SSH directory for the root user
- name: Create SSH directory for the root user
  file:
    path: "/{{ ANSIBLE_USER }}/.ssh"
    state: directory
    mode: '0700'
  tags: ['ssh']

# Add SSH key to root user's authorized_keys
- name: Add SSH key to root user's authorized_keys
  authorized_key:
    user: "{{ ANSIBLE_USER }}"
    key: "{{ lookup('file', SSH_KEY_PATH) }}"
    state: present
  tags: ['ssh']

# Configure SSH daemon for security
- name: Configure secure SSH configuration
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  loop:
    - { regexp: '^#?PermitRootLogin', line: 'PermitRootLogin prohibit-password' } 
    - { regexp: '^#?PasswordAuthentication', line: 'PasswordAuthentication no' }  # Disable password auth
    - { regexp: '^#?ChallengeResponseAuthentication', line: 'ChallengeResponseAuthentication no' }  # Disable challenge-response auth
    - { regexp: '^#?UsePAM', line: 'UsePAM no' }  # Disable PAM authentication
    - { regexp: '^#?PubkeyAuthentication', line: 'PubkeyAuthentication yes' }  # Ensure public key authentication is enabled
  notify: restart ssh  # Triggers SSH service restart when config changes
  tags: ['ssh']

# Create custom SSH config
- name: Create custom SSH config
  copy:
    src: 99-custom.conf
    dest: /etc/ssh/sshd_config.d/99-custom.conf
    mode: '0644'
  notify: restart ssh
  tags: ['ssh']
